In [100]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [116]:
data=pd.read_csv("weather_classification_data.csv")
data

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,overcast,1003.15,1,Summer,1.0,mountain,Rainy
13196,-1.0,76,3.5,23.0,cloudy,1067.23,1,Winter,6.0,coastal,Snowy
13197,30.0,77,5.5,28.0,overcast,1012.69,3,Autumn,9.0,coastal,Cloudy
13198,3.0,76,10.0,94.0,overcast,984.27,0,Winter,2.0,inland,Snowy
13199,-5.0,38,0.0,92.0,overcast,1015.37,5,Autumn,10.0,mountain,Rainy

In [117]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [118]:
data["Cloud Cover"]=le.fit_transform(data["Cloud Cover"])
data

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14.0,73,9.5,82.0,3,1010.82,2,Winter,3.5,inland,Rainy
1,39.0,96,8.5,71.0,3,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,0,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,0,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,2,990.67,1,Winter,2.5,mountain,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,2,1003.15,1,Summer,1.0,mountain,Rainy
13196,-1.0,76,3.5,23.0,1,1067.23,1,Winter,6.0,coastal,Snowy
13197,30.0,77,5.5,28.0,2,1012.69,3,Autumn,9.0,coastal,Cloudy
13198,3.0,76,10.0,94.0,2,984.27,0,Winter,2.0,inland,Snowy
13199,-5.0,38,0.0,92.0,2,1015.37,5,Autumn,10.0,mountain,Rainy

In [119]:
data["Season"]=le.fit_transform(data["Season"])
data

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14.0,73,9.5,82.0,3,1010.82,2,3,3.5,inland,Rainy
1,39.0,96,8.5,71.0,3,1011.43,7,1,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,0,1018.72,5,1,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,0,1026.25,7,1,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,2,990.67,1,3,2.5,mountain,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,2,1003.15,1,2,1.0,mountain,Rainy
13196,-1.0,76,3.5,23.0,1,1067.23,1,3,6.0,coastal,Snowy
13197,30.0,77,5.5,28.0,2,1012.69,3,0,9.0,coastal,Cloudy
13198,3.0,76,10.0,94.0,2,984.27,0,3,2.0,inland,Snowy
13199,-5.0,38,0.0,92.0,2,1015.37,5,0,10.0,mountain,Rainy

In [120]:
data["Location"]=le.fit_transform(data["Location"])
data

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14.0,73,9.5,82.0,3,1010.82,2,3,3.5,1,Rainy
1,39.0,96,8.5,71.0,3,1011.43,7,1,10.0,1,Cloudy
2,30.0,64,7.0,16.0,0,1018.72,5,1,5.5,2,Sunny
3,38.0,83,1.5,82.0,0,1026.25,7,1,1.0,0,Sunny
4,27.0,74,17.0,66.0,2,990.67,1,3,2.5,2,Rainy
...,...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,2,1003.15,1,2,1.0,2,Rainy
13196,-1.0,76,3.5,23.0,1,1067.23,1,3,6.0,0,Snowy
13197,30.0,77,5.5,28.0,2,1012.69,3,0,9.0,0,Cloudy
13198,3.0,76,10.0,94.0,2,984.27,0,3,2.0,1,Snowy
13199,-5.0,38,0.0,92.0,2,1015.37,5,0,10.0,2,Rainy

In [121]:
data["Location"].value_counts()

Location
1    4816
2    4813
0    3571
Name: count, dtype: int64

In [122]:
#data.replace({"Season":{"Winter":0,"Spring":1,"Summer":2,"Autumn":3}},inplace=True)

In [123]:
#data.replace({"Location":{"inland":0,"mountain":1,"coastal":2}},inplace=True)

In [124]:
#data.replace({"Cloud Cover":{"clear":0,"partly cloudy":1,"overcast":2}},inplace=True)

In [125]:
#data.replace({"Weather Type":{"Sunny":0,"Cloudy":1,"Rainy":2}},inplace=True)

In [126]:
x=data.drop("Weather Type",axis=1)
y=data["Weather Type"]

In [127]:
x

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location
0,14.0,73,9.5,82.0,3,1010.82,2,3,3.5,1
1,39.0,96,8.5,71.0,3,1011.43,7,1,10.0,1
2,30.0,64,7.0,16.0,0,1018.72,5,1,5.5,2
3,38.0,83,1.5,82.0,0,1026.25,7,1,1.0,0
4,27.0,74,17.0,66.0,2,990.67,1,3,2.5,2
...,...,...,...,...,...,...,...,...,...,...
13195,10.0,74,14.5,71.0,2,1003.15,1,2,1.0,2
13196,-1.0,76,3.5,23.0,1,1067.23,1,3,6.0,0
13197,30.0,77,5.5,28.0,2,1012.69,3,0,9.0,0
13198,3.0,76,10.0,94.0,2,984.27,0,3,2.0,1
13199,-5.0,38,0.0,92.0,2,1015.37,5,0,10.0,2

In [128]:
y

0         Rainy
1        Cloudy
2         Sunny
3         Sunny
4         Rainy
          ...
13195     Rainy
13196     Snowy
13197    Cloudy
13198     Snowy
13199     Rainy
Name: Weather Type, Length: 13200, dtype: object

In [129]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.4,random_state=45)

In [130]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [131]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=7)
classifier.fit(x_train,y_train) #Training
y_pred = classifier.predict(x_test)

In [132]:
y_pred

array(['Rainy', 'Cloudy', 'Rainy', ..., 'Sunny', 'Snowy', 'Rainy'],
      dtype=object)

In [134]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_pred,y_test))

0.8952651515151515

In [136]:
print(confusion_matrix(y_pred,y_test))

[[1168   87   45   80]
 [ 103 1207   32   42]
 [  28   34 1222   16]
 [  34   25   27 1130]]

In [141]:
classifier.predict([[67,37,9.66,35,97.99,23,0.76,8.46,36,23.4]])

array(['Sunny'], dtype=object)